### ISSUE TITLE
Look at google protobuf for serialisation.

### ISSUE THREAD

**Issue by jhidding** [NLeSC/noodles#22]
https://developers.google.com/protocol-buffers/docs/pythontutorial#why-use-protocol-buffers

**Comment by blootsvoets** [comment]
FYI Avro serialisation is commonly used for data types that are expected to evolve (and for dynamic languages such as python).
https://martin.kleppmann.com/2012/12/05/schema-evolution-in-avro-protocol-buffers-thrift.html
It's also one of the standard formats for Apache Spark.

**Comment by jhidding** [comment]
Ok! thanks, I'll take a look at using that. Then compare performance with JSON.

**Comment by blootsvoets** [comment]
JSON performance will probably be faster but lack compression. Main difference with Protobuf or Avro is the complete lack of a schema.

See https://github.com/eishay/jvm-serializers/wiki for benchmarks and serialiser types.
