### ISSUE TITLE
setup.py should include install_requires=['numpy',]

### ISSUE THREAD

**Issue by oscarmartinezrubi** [NLeSC/noodles#25]

**Comment by jhidding** [comment]
Actually the dependency on numpy should be optional. Does something fail without numpy?

**Comment by oscarmartinezrubi** [comment]
as far as I remember, "pip install ." failed. I had to manually install numpy before noodles

**Comment by jhidding** [comment]
In the `devel` branch, "pip install ." works without any 3rd party python packages, and most unittests (those that don't use numpy) run fine. So I'll just close this issue.
