### ISSUE TITLE
Is Lift a Monadic operation.

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/noodles#27]
Is it **lift** a monadic operation? if it is,  what monad is it lifting to?

Just to make it clear to myself, let's use some Haskell terminology.

In Haskell Terms  lift  is defined by

`liftM :: Monad m => (a1 -> r) -> m a1 -> m r`

And returns by

`return:: Monad m => a -> m a`

I think that your `lift` is more like ``return`` in Haskell in the sense that it lifts a pure computations to whatever monad you are using. Am I right?

**Comment by jhidding** [comment]
Hmmm I guess ;) The name stays
