### ISSUE TITLE
Unable to find the Xenon module

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/noodles#32]
Due to a limitation in the way the Python 3 uses both `sys.path` and the `__init__.py` files inside a package, the python interpreter only see the modules that are inside the `run` directory but it can't reach the `xenon` subfolder and the modules inside.

For More information refer to  [init-trap](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html)

The only solution that I see is to move all the content from the subfolder `xenon` to its parent `run`.

**Comment by jhidding** [comment]
That's weird. Is 'noodles.run.xenon' in the modules in setup.py?

**Comment by felipeZ** [comment]
I have added it
