### ISSUE TITLE
python is not installing extras_require

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/noodles#41]
Python is not installing the ``numpy`` dependencies from the [setup.py](https://github.com/NLeSC/noodles/blob/devel/setup.py)
```python
    extras_require={
        'prov': ['tinydb'],
        'xenon': ['pyxenon'],
        'numpy': ['numpy', 'h5py', 'msgpack-python', 'filelock'],
        'test': ['nose', 'coverage', 'pyflakes', 'pep8', 'docker-py']
    },
```

**Comment by jhidding** [comment]
You can install the extras by doing
```
> pip install .[prov,xenon,numpy] -U
```
from the repositorie's root folder.

**Comment by felipeZ** [comment]
That's not the point, I can do that. I don't want the libraries that depend on Noodles to add extra-dependencies that are inside the noodles.

**Comment by jhidding** [comment]
I don't understand what you mean, in QMWorks you should be able to say
```python
install_requires=[
     'noodles[prov,xenon,numpy]', ...
]
```
in `setup.py`; that should settle all dependcies in noodles...

**Comment by felipeZ** [comment]
I misunderstood something, thanks!
