### ISSUE TITLE
Link to the iPython notebook mentioned in 'First steps' of the documentation

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/noodles#49]
The documentation mentions that the 'First steps' are available as an iPython notebook, but is does not mention where it is available. I would expect a link there, or at least some explanation on where to find it.

**Comment by vincentvanhees** [comment]
I added an explicit hyperlink in the documentation-branch. I am now looking into https://nbsphinx.readthedocs.io/en/0.2.14/ for a more elegant solution
