### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by jhidding** [NLeSC/noodles#5]
Merge Fireworks support and document it.

**Comment by wrvhage** [comment]
Waarom krijg ik de Vijf Geboden des Noodles toegemaild?

PS zalig kerstfeest

Willem

| Dr. Willem van Hage | Senior eScience Research Engineer | email: <mailto:w.vanhage@esciencecenter.nl> w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl> | +31-615886039<tel:+31-615886039> |
| Netherlands eScience Center | Science Park 140<x-apple-data-detectors://2> | 1098 XG Amsterdam<x-apple-data-detectors://3> | The Netherlands | wrvhage.nl<http://wrvhage.nl/> |
| The Netherlands eScience Center is a joint initiative by SURF and NWO | <http://www.nlesc.nl/> www.nlesc.nl<http://www.nlesc.nl/> |


On 24 Dec 2015, at 20:08, Johannes Hidding <notifications@github.com<mailto:notifications@github.com>> wrote:


Merge Fireworks support and document it.

-

**Comment by jhidding** [comment]
Ja, mailtjes zijn irritant. Ik zat gewoon een paar issues aan te maken. Ik
zal kijken of ik zelf iets kan veranderen in de settings op github.
Zalig kerstfeest!

Op do 24 dec. 2015 om 22:48 schreef Willem Robert van Hage <
notifications@github.com>:

> Waarom krijg ik de Vijf Geboden des Noodles toegemaild?
>
> PS zalig kerstfeest
>
> Willem
>
> | Dr. Willem van Hage | Senior eScience Research Engineer | email: <mailto:
> w.vanhage@esciencecenter.nl> w.vanhage@esciencecenter.nl<mailto:
> w.vanhage@esciencecenter.nl> | +31-615886039<tel:+31-615886039> |
> | Netherlands eScience Center | Science Park
> 140<x-apple-data-detectors://2> | 1098 XG
> Amsterdam<x-apple-data-detectors://3> | The Netherlands | wrvhage.nl<
> http://wrvhage.nl/> |
> | The Netherlands eScience Center is a joint initiative by SURF and NWO | <
> http://www.nlesc.nl/> www.nlesc.nl<http://www.nlesc.nl/> |
>
>
> On 24 Dec 2015, at 20:08, Johannes Hidding <notifications@github.com

**Comment by wrvhage** [comment]
Geen probleem hoor. Vroeg me af waarom ik ze kreeg, maar snap het nu.

| Dr. Willem van Hage | Senior eScience Research Engineer | email: w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl> |
| Netherlands eScience Center | Science Park 140 | 1098 XG Amsterdam | The Netherlands |
| The Netherlands eScience Center is a joint initiative by SURF and NWO | www.nlesc.nl<http://www.nlesc.nl> <http://www.esciencecenter.nl/> |

On 25 Dec 2015, at 10:52, Johannes Hidding <notifications@github.com<mailto:notifications@github.com>> wrote:

Ja, mailtjes zijn irritant. Ik zat gewoon een paar issues aan te maken. Ik
zal kijken of ik zelf iets kan veranderen in de settings op github.
Zalig kerstfeest!

Op do 24 dec. 2015 om 22:48 schreef Willem Robert van Hage <
notifications@github.com<mailto:notifications@github.com>>:

> Waarom krijg ik de Vijf Geboden des Noodles toegemaild?
>
> PS zalig kerstfeest
>
> Willem
>
> | Dr. Willem van Hage | Senior eScience Research Engineer | email: <mailto:
> w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl>> w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl><mailto:
> w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl>> | +31-615886039<tel:+31-615886039> |
> | Netherlands eScience Center | Science Park
> 140<x-apple-data-detectors://2> | 1098 XG
> Amsterdam<x-apple-data-detectors://3> | The Netherlands | wrvhage.nl<http://wrvhage.nl><
> http://wrvhage.nl/> |
> | The Netherlands eScience Center is a joint initiative by SURF and NWO | <
> http://www.nlesc.nl/> www.nlesc.nl<http://www.nlesc.nl><http://www.nlesc.nl/> |
>
>
> On 24 Dec 2015, at 20:08, Johannes Hidding <notifications@github.com<mailto:notifications@github.com>
