### ISSUE TITLE
API functions accumulate() & gather() seem redundant

### ISSUE THREAD

**Issue by arnikz** [NLeSC/noodles#56]
Following the second example of the [user doc](https://github.com/NLeSC/noodles/blob/master/doc/source/eating.rst), would it be possible to simplify (code line no. 13)?

`x = accumulate(gather(*w))` -> `x = gather(*w)`

`accumulate` and `gather` seem redundant to me as a user, am I missing something?

**Comment by arnikz** [comment]
and in the [figure](https://github.com/NLeSC/noodles/blob/master/doc/source/_static/images/dag2.png) shouldn't be *sum* replaced by *accumulate* instead?

**Comment by jhidding** [comment]
Ok, the figure is not up-to-date with the text; `accumulate` does the same as sum, but in a wrapped form. It is possible, but not so nice to just also call this function `sum`. It will sum the elements in a list. To make a list promise, we have to call the `gather` function. I could have done:

```python
@schedule
def accumulate(*numbers):
    return sum(numbers)
```

Take this further, it means we would have to redesign every function that takes a list as an argument. I want to keep it clear what we are doing.
